// <auto-generated />
using EjercicioBBDDAgenda.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EjercicioBBDDAgenda.Migrations
{
    [DbContext(typeof(AgendaContext))]
    [Migration("20200622131451_MigracionTablas")]
    partial class MigracionTablas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EjercicioBBDDAgenda.Clases.Cita", b =>
                {
                    b.Property<int>("CitaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContactoId");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Fecha");

                    b.Property<string>("Hora");

                    b.HasKey("CitaId");

                    b.HasIndex("ContactoId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("EjercicioBBDDAgenda.Clases.Contacto", b =>
                {
                    b.Property<int>("ContactoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos");

                    b.Property<string>("Localidad");

                    b.Property<string>("Nombre");

                    b.Property<int>("Telefono");

                    b.HasKey("ContactoID");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("EjercicioBBDDAgenda.Clases.Cita", b =>
                {
                    b.HasOne("EjercicioBBDDAgenda.Clases.Contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
